### ISSUE TITLE
missing files *labelTrainIds.png

### ISSUE THREAD

**Issue by liyunsheng13** [Raykoooo/IAST#4]
Hi 
Thanks for the good work. When I try to use the code, I got the missing file error that shows all the file with name *labelTrainIds.png from the cityscape dataset are missing. The ground truth files I can find have name without 'Train'. Could you help me check whether they are the same files or not. 

If the files are the same, when I try to use your code I find after training the model with 800 iterations, I can only get mIOU 0.0049, which seems to be something wrong. I just use the file 'run_gtav2cityscapes_self_traing_only_t4.sh' with the pertained model you released.

Thanks
Yunsheng

**Comment by Raykoooo** [comment]
This issue: https://github.com/Raykoooo/IAST/issues/3

**Comment by liyunsheng13** [comment]
It works. I have another question about data loading. I find while images are resized, some error like "ValueError: Requested crop size (870, 1740) is larger than the image size (697, 1276)" occurs occasionally. Do you meet the similar problem?

**Comment by lrjing** [comment]
Hello, thank you very much for your open source code.
Because of the limited capacity of the GPU, I can only use the weights that you trained with the graphics card T4.
I ran the GTA5 dataset and it was similar to yours.
This is because GitHub has not yet updated the weight of T4 for the Synthia dataset. So I trained this part from scratch.When I started training from scratch, I found that the results were a little poor.I don't understand this question, so I want to consult you.I would also like to ask when you can update the training weights for the Synthia dataset.
Thank you very much.

**Comment by Raykoooo** [comment]
> It works. I have another question about data loading. I find while images are resized, some error like "ValueError: Requested crop size (870, 1740) is larger than the image size (697, 1276)" occurs occasionally. Do you meet the similar problem?

This is a bug caused by "RandomSizedCrop", I haven't fixed it yet.
